import 'package:sdk/language.dart';
import 'package:sdk/xlocal.dart';

class XLocal extends XBaseLocal {
  final _dict = {
    AppLanguge.en: {
      'license_editor_title': 'License',
      'license_editor_company_type': 'Type',
      'license_editor_company': 'Company',
      'license_editor_sign': 'Sign',
      'license_editor_valid_period': 'Period:',
      'license_editor_address': 'Address',
      'license_editor_postcode': 'Post code',
      'license_editor_city': 'City',
      'license_editor_telephone': 'Telephone',
      'license_editor_siret': 'Siret',
      'license_editor_apeCode': 'APE CODE',
      'license_editor_rcs': 'RCS',
      'license_editor_greffe': 'Greffe du:',
      'license_editor_vatNumber': 'VAT N°',
      'license_editor_capital': 'Capital',
      'license_editor_ok': 'OK',
    },
    AppLanguge.fr: {
      'license_editor_title': 'License',
      'license_editor_company_type': 'Type',
      'license_editor_company': 'Société',
      'license_editor_sign': 'L\'ensiengne',
      'license_editor_valid_period': 'Periode:',
      'license_editor_address': 'Adresse',
      'license_editor_postcode': 'Code postale',
      'license_editor_city': 'Ville',
      'license_editor_telephone': 'Telephone',
      'license_editor_siret': 'SIRET',
      'license_editor_apeCode': 'APE CODE',
      'license_editor_rcs': 'RCS',
      'license_editor_greffe': 'Greffe du:',
      'license_editor_vatNumber': 'N° TVA',
      'license_editor_capital': 'Capital',
      'license_editor_ok': 'OK',
    },
    AppLanguge.zh: {
      'license_editor_title': 'License',
      'license_editor_company_type': '公司类型',
      'license_editor_company': '公司名称',
      'license_editor_sign': '招牌',
      'license_editor_valid_period': '有效期:',
      'license_editor_address': '地址',
      'license_editor_postcode': '邮编',
      'license_editor_city': '城市',
      'license_editor_telephone': '电话',
      'license_editor_siret': 'SIRET',
      'license_editor_apeCode': 'APE CODE',
      'license_editor_rcs': 'RCS',
      'license_editor_greffe': 'Greffe du:',
      'license_editor_vatNumber': 'N° TVA',
      'license_editor_capital': 'Capital',
      'license_editor_ok': '确认',
    },
    AppLanguge.ko: {
      'license_editor_title': 'License',
      'license_editor_company_type': '회사 유형',
      'license_editor_company': '회사 이름',
      'license_editor_sign': '가게 이름',
      'license_editor_valid_period': '유효기간:',
      'license_editor_address': '주소',
      'license_editor_postcode': '우편번호',
      'license_editor_city': '도시',
      'license_editor_telephone': '전화번호',
      'license_editor_siret': 'Siret',
      'license_editor_apeCode': 'APE CODE',
      'license_editor_rcs': 'RCS',
      'license_editor_greffe': 'Greffe du:',
      'license_editor_vatNumber': 'VAT N°',
      'license_editor_capital': 'Capital',
      'license_editor_ok': '확인',
    },
    AppLanguge.ja: {
      'license_editor_title': 'License',
      'license_editor_company_type': '会社タイプ',
      'license_editor_company': '会社名',
      'license_editor_sign': 'サイン',
      'license_editor_valid_period': '有効期間:',
      'license_editor_address': '住所',
      'license_editor_postcode': '郵便番号',
      'license_editor_city': '都市名',
      'license_editor_telephone': '電話番号',
      'license_editor_siret': 'Siret',
      'license_editor_apeCode': 'APE CODE',
      'license_editor_rcs': 'RCS',
      'license_editor_greffe': 'Greffe du:',
      'license_editor_vatNumber': 'VAT N°',
      'license_editor_capital': 'Capital',
      'license_editor_ok': '確認',
    },
  };
  @override
  Map<String, Map<String, String>> get keys => _dict;

  @override
  // TODO: implement name
  String get name => 'license_editor_';
}
