import 'package:sdk/language.dart';
import 'package:sdk/xlocal.dart';

class XLocal extends XBaseLocal {
  final _dict = {
    AppLanguge.en: {
      'terminal_title': 'Terminal',
      'terminal_hid': 'Hid',
      'terminal_name': 'Name',
      'terminal_services': 'Services',
      'terminal_categories': 'Categories',
      'terminal_tabletMode': 'Tablet mode',
      'terminal_pcMode': 'PC mode',
      'terminal_classicMode': 'Classic mode',
      'terminal_rapidMode': 'Rapid mode',
      'terminal_cachedData': 'Cached data',
      'terminal_dataFromServer': 'Data from server',
      'terminal_input_with_quantity': 'Input quantity',
      'terminal_active': 'Acitve',
      'terminal_OK': 'OK',
      'terminal_delete': 'Delete',
      'terminal_confirm': 'Confirm',
      'terminal_confirmContent': 'Are you sur to delete this terminal?',
    },
    AppLanguge.fr: {
      'terminal_title': 'Terminal',
      'terminal_hid': 'Hid',
      'terminal_name': 'Nom',
      'terminal_services': 'Services',
      'terminal_categories': 'Categories',
      'terminal_tabletMode': 'Tablette mode',
      'terminal_pcMode': 'PC mode',
      'terminal_classicMode': 'Mode classic',
      'terminal_rapidMode': 'Mode rapide',
      'terminal_cachedData': 'Données en cache',
      'terminal_dataFromServer': 'Données de server',
      'terminal_input_with_quantity': 'Saisir quantité',
      'terminal_active': 'Acitve',
      'terminal_OK': 'OK',
      'terminal_delete': 'Supprimer',
      'terminal_confirm': 'Confirmation',
      'terminal_confirmContent': 'Vous etes sur de supprimer le terminal?',
    },
    AppLanguge.zh: {
      'terminal_title': '终端设置',
      'terminal_hid': '设备ID',
      'terminal_name': '名称',
      'terminal_services': '服务类型',
      'terminal_categories': '产品目录',
      'terminal_tabletMode': '平板模式',
      'terminal_pcMode': 'PC模式',
      'terminal_classicMode': '队列模式',
      'terminal_rapidMode': '快速模式',
      'terminal_cachedData': '缓存数据',
      'terminal_dataFromServer': '服务器数据',
      'terminal_input_with_quantity': '输入数量',
      'terminal_active': '可用',
      'terminal_OK': '确认',
      'terminal_delete': '删除',
      'terminal_confirm': '不可逆操作',
      'terminal_confirmContent': '您确定要删除该终端?',
    },
    AppLanguge.ko: {
      'terminal_title': '터미널 설정',
      'terminal_hid': '설비ID',
      'terminal_name': '명칭',
      'terminal_services': '서비스 유형',
      'terminal_categories': 'Categories',
      'terminal_tabletMode': '태블릿 모드',
      'terminal_pcMode': 'PC 모드',
      'terminal_classicMode': '클래식 모드',
      'terminal_rapidMode': '단축 모드',
      'terminal_cachedData': 'Cached data',
      'terminal_dataFromServer': 'Données de server',
      'terminal_input_with_quantity': '수량 입력',
      'terminal_active': '활성화',
      'terminal_OK': '확인',
      'terminal_delete': '삭제',
      'terminal_confirm': '확정',
      'terminal_confirmContent': '이 터미널을 삭제하겠습니까?',
    },
    AppLanguge.ja: {
      'terminal_title': 'ターミナル設置',
      'terminal_hid': '設備ID',
      'terminal_name': '名前',
      'terminal_services': 'サーバータイプ',
      'terminal_categories': 'Categories',
      'terminal_tabletMode': 'タブレットモード',
      'terminal_pcMode': 'PCモード',
      'terminal_classicMode': '隊列モード',
      'terminal_rapidMode': '快速モード',
      'terminal_cachedData': 'Cached data',
      'terminal_dataFromServer': 'Données de server',
      'terminal_input_with_quantity': '数を入力',
      'terminal_active': '使用可能',
      'terminal_OK': '確認',
      'terminal_delete': '消す',
      'terminal_confirm': '変更不可',
      'terminal_confirmContent': 'このファイルを消しますか?',
    },
  };
  @override
  Map<String, Map<String, String>> get keys => _dict;

  @override
  String get name => 'terminal_';
}
