import 'package:sdk/language.dart';
import 'package:sdk/xlocal.dart';

class XLocal extends XBaseLocal {
  final _dict = {
    AppLanguge.en: {
      'first_start_create_user': 'Create Super user',
      'first_start_company_info': 'Company information',
      'first_start_confirm': 'Confirm',
      'first_start_user_name': 'User Name',
      'first_start_login': 'Id',
      'first_start_password': 'Password',
      'first_start_company_siren': 'SIREN',
      'first_start_company_invoice': 'Invoice',
      'first_start_company_proof': 'Proof',
      'first_start_company_type': 'Type',
      'first_start_company_name': 'Company name',
      'first_start_sign': 'Sign',
      'first_start_address': 'Address',
      'first_start_post_code': 'Post code',
      'first_start_city': 'City',
      'first_start_telephone': 'Telephone',
      'first_start_siret': 'SIRET',
      'first_start_RCS': 'RCS',
      'first_start_greffe': 'Greffe du:',
      'first_start_APE': 'APE',
      'first_start_vat': 'VAT',
      'first_start_capital': 'Capital',
      'first_start_prev': 'Precedent',
      'first_start_next': 'Next',
      'first_start_submit': 'Submit',
      'first_start_account': 'Account',
    },
    AppLanguge.fr: {
      'first_start_create_user': 'Creattion Supeur user',
      'first_start_company_info': 'Information de societe',
      'first_start_confirm': 'Confirmation',
      'first_start_user_name': 'Nom de Supeur user',
      'first_start_login': 'Identifiant',
      'first_start_password': 'Mots de passe',
      'first_start_company_siren': 'SIREN',
      'first_start_company_invoice': 'Facture',
      'first_start_company_proof': 'Justificatif',
      'first_start_company_type': 'Type',
      'first_start_company_name': 'Nom de societe',
      'first_start_sign': 'l\'enseigne',
      'first_start_address': 'Adresse',
      'first_start_post_code': 'Code postale',
      'first_start_city': 'Ville',
      'first_start_telephone': 'Telephone',
      'first_start_siret': 'SIRET',
      'first_start_RCS': 'RCS',
      'first_start_greffe': 'Greffe du:',
      'first_start_APE': 'APE',
      'first_start_vat': 'TVA',
      'first_start_capital': 'Capital',
      'first_start_prev': 'Précédent',
      'first_start_next': 'Suivant',
      'first_start_submit': 'Soumettre',
      'first_start_account': 'Compte',
    },
    AppLanguge.zh: {
      'first_start_create_user': '超级管理员账号',
      'first_start_company_info': '公司信息',
      'first_start_confirm': '确认',
      'first_start_user_name': '姓名',
      'first_start_login': '账号',
      'first_start_password': '密码',
      'first_start_company_siren': 'SIREN',
      'first_start_company_invoice': '发票',
      'first_start_company_proof': '就餐证明',
      'first_start_company_type': '公司类型',
      'first_start_company_name': '公司名称',
      'first_start_sign': '招牌名称',
      'first_start_address': '地址',
      'first_start_post_code': '邮编',
      'first_start_city': '城市',
      'first_start_telephone': '电话',
      'first_start_siret': 'SIRET',
      'first_start_RCS': 'RCS',
      'first_start_greffe': 'Greffe du:',
      'first_start_APE': 'APE',
      'first_start_vat': 'TVA',
      'first_start_capital': 'Capital',
      'first_start_prev': '前一页',
      'first_start_next': '下一页',
      'first_start_submit': '提交',
      'first_start_account': '账号信息',
    },
    AppLanguge.ko: {
      'first_start_create_user': '관리자 아이디',
      'first_start_company_info': '화사 정보',
      'first_start_confirm': '확인',
      'first_start_user_name': '사용자 이름',
      'first_start_login': '아이디',
      'first_start_password': '비밀번호',
      'first_start_company_siren': 'SIREN',
      'first_start_company_invoice': '영수증',
      'first_start_company_proof': '증명',
      'first_start_company_type': '회사 유형',
      'first_start_company_name': '회사 이름',
      'first_start_sign': '사인',
      'first_start_address': '주소',
      'first_start_post_code': '우편 번호',
      'first_start_city': '도시',
      'first_start_telephone': '전화',
      'first_start_siret': 'SIRET',
      'first_start_RCS': 'RCS',
      'first_start_greffe': 'Greffe du:',
      'first_start_APE': 'APE',
      'first_start_vat': 'VAT',
      'first_start_capital': 'Capital',
      'first_start_prev': '이전',
      'first_start_next': '이후',
      'first_start_submit': '제출',
      'first_start_account': '아이디 정보',
    },
    AppLanguge.ja: {
      'first_start_create_user': '上級管理員作成',
      'first_start_company_info': '会社情報',
      'first_start_confirm': '確認',
      'first_start_user_name': '名前',
      'first_start_login': 'Id',
      'first_start_password': 'パスワード',
      'first_start_company_siren': 'SIREN',
      'first_start_company_invoice': '領収書',
      'first_start_company_proof': 'お食事証明',
      'first_start_company_type': 'タイプ',
      'first_start_company_name': '会社名',
      'first_start_sign': 'Sign',
      'first_start_address': '住所',
      'first_start_post_code': '郵便番号',
      'first_start_city': '都市名',
      'first_start_telephone': '電話番号',
      'first_start_siret': 'SIRET',
      'first_start_RCS': 'RCS',
      'first_start_greffe': 'Greffe du:',
      'first_start_APE': 'APE',
      'first_start_vat': 'VAT',
      'first_start_capital': 'Capital',
      'first_start_prev': 'Precedent',
      'first_start_next': 'Next',
      'first_start_submit': 'Submit',
      'first_start_account': 'Account',
    },
  };
  @override
  Map<String, Map<String, String>> get keys => _dict;

  @override
  String get name => 'first_start_';
}
